# Generated by Django 4.2 on 2023-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_category_remove_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
