# Generated by Django 4.2 on 2023-04-04 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_delete_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 18, 45, 31, 837178, tzinfo=datetime.timezone.utc)),
        ),
    ]
