# Generated by Django 4.2 on 2023-04-04 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 18, 52, 43, 712779, tzinfo=datetime.timezone.utc)),
        ),
    ]
