# Generated by Django 4.2 on 2023-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
